name: example
description: GetFlutter Demo app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getflutter:
    path: ../
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.1
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/github.svg
    - lib/assets/logo.svg
    - lib/assets/playstore.svg
