name: example
description: GetFlutter Demo app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getflutter:
    path: ../

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: icomoon
      fonts:
        - asset: lib/fonts/icomoon.ttf

  assets:
    - lib/assets/food.jpeg
    - lib/assets/img.png
    - lib/assets/heart.png
    - lib/assets/heart_border.png
    - lib/assets/heart_half.png
